import 'package:flutter/material.dart';

/// A pinball table theme: real physical materials — woods, felts, leathers,
/// brass and ivory. No neon, no cyberpunk, no gradients-as-decoration.
@immutable
class PinballThemeDef {
  final String id;
  final String name;
  final bool isPro;
  final Color woodDark; // cabinet rails / outer frame
  final Color woodMid; // playfield apron
  final Color woodLight; // trim highlights
  final Color felt; // playfield surface
  final Color rail; // wall / guide color
  final Color bumperA;
  final Color bumperB;
  final Color sling;
  final Color laneLit;
  final Color laneUnlit;
  final Color flipper;
  final Color ivory; // primary text
  final Color muted; // secondary text
  final Color accent; // UI accent

  const PinballThemeDef({
    required this.id,
    required this.name,
    this.isPro = false,
    required this.woodDark,
    required this.woodMid,
    required this.woodLight,
    required this.felt,
    required this.rail,
    required this.bumperA,
    required this.bumperB,
    required this.sling,
    required this.laneLit,
    required this.laneUnlit,
    required this.flipper,
    required this.ivory,
    required this.muted,
    required this.accent,
  });
}

class PinballThemes {
  static const List<PinballThemeDef> all = [
    PinballThemeDef(
      id: 'classic-oak',
      name: 'Classic Oak',
      woodDark: Color(0xFF3B2416),
      woodMid: Color(0xFF6B4423),
      woodLight: Color(0xFF9C6B3F),
      felt: Color(0xFF1E4D3B),
      rail: Color(0xFF8A6D3B),
      bumperA: Color(0xFFC9A227),
      bumperB: Color(0xFFA31621),
      sling: Color(0xFFD9B36A),
      laneLit: Color(0xFFFFD76A),
      laneUnlit: Color(0xFF5A4A33),
      flipper: Color(0xFFD9B36A),
      ivory: Color(0xFFF5EFE0),
      muted: Color(0xFFB9A98A),
      accent: Color(0xFFC9A227),
    ),
    PinballThemeDef(
      id: 'dark-walnut',
      name: 'Dark Walnut',
      woodDark: Color(0xFF241309),
      woodMid: Color(0xFF4A2C17),
      woodLight: Color(0xFF7A5230),
      felt: Color(0xFF16382A),
      rail: Color(0xFF6B4A2C),
      bumperA: Color(0xFFD9B36A),
      bumperB: Color(0xFF7A1F1F),
      sling: Color(0xFFB98A4A),
      laneLit: Color(0xFFFFE08A),
      laneUnlit: Color(0xFF4A3A28),
      flipper: Color(0xFFC99B5F),
      ivory: Color(0xFFF2EAD8),
      muted: Color(0xFFA8926E),
      accent: Color(0xFFD9A441),
    ),
    PinballThemeDef(
      id: 'cherry',
      name: 'Cherry Redwood',
      woodDark: Color(0xFF3A1408),
      woodMid: Color(0xFF6E2A14),
      woodLight: Color(0xFF9C4A2A),
      felt: Color(0xFFEFE3C8),
      rail: Color(0xFF7A3A1E),
      bumperA: Color(0xFFB03A2E),
      bumperB: Color(0xFF2E5E4E),
      sling: Color(0xFFC46A3A),
      laneLit: Color(0xFFFF6B4A),
      laneUnlit: Color(0xFF8A6A4A),
      flipper: Color(0xFF8A2E1E),
      ivory: Color(0xFF2E1A0E),
      muted: Color(0xFF7A5A42),
      accent: Color(0xFFB03A2E),
    ),
    PinballThemeDef(
      id: 'maple',
      name: 'Maple Honey',
      woodDark: Color(0xFF5A3A1E),
      woodMid: Color(0xFF8A5E2E),
      woodLight: Color(0xFFC99B5F),
      felt: Color(0xFF1F3A5E),
      rail: Color(0xFF9C7A4A),
      bumperA: Color(0xFFE8B64C),
      bumperB: Color(0xFF2E5E8A),
      sling: Color(0xFFD9A441),
      laneLit: Color(0xFFFFE08A),
      laneUnlit: Color(0xFF6A5A3A),
      flipper: Color(0xFFE8B64C),
      ivory: Color(0xFFF8F2E4),
      muted: Color(0xFFC2B08E),
      accent: Color(0xFFE8B64C),
    ),
    PinballThemeDef(
      id: 'midnight',
      name: 'Midnight Parlor',
      woodDark: Color(0xFF14100C),
      woodMid: Color(0xFF2E2418),
      woodLight: Color(0xFF5A4A30),
      felt: Color(0xFF1A2440),
      rail: Color(0xFF4A3E28),
      bumperA: Color(0xFFC9A227),
      bumperB: Color(0xFF5E2E8A),
      sling: Color(0xFF9C8A5A),
      laneLit: Color(0xFFFFD76A),
      laneUnlit: Color(0xFF3A3428),
      flipper: Color(0xFFB99B5A),
      ivory: Color(0xFFF0EAD8),
      muted: Color(0xFF9A8E72),
      accent: Color(0xFFC9A227),
    ),
    PinballThemeDef(
      id: 'barnwood',
      name: 'Rustic Barnwood',
      woodDark: Color(0xFF3A332A),
      woodMid: Color(0xFF5E5546),
      woodLight: Color(0xFF8A7E68),
      felt: Color(0xFF4A3E2A),
      rail: Color(0xFF6E6252),
      bumperA: Color(0xFFC46A3A),
      bumperB: Color(0xFF6E8A3A),
      sling: Color(0xFFA88A5A),
      laneLit: Color(0xFFFFC46A),
      laneUnlit: Color(0xFF5E5546),
      flipper: Color(0xFFC49B6A),
      ivory: Color(0xFFF5EEDC),
      muted: Color(0xFFB4A88E),
      accent: Color(0xFFC46A3A),
    ),
    // ---------------- Pro themes ----------------
    PinballThemeDef(
      id: 'emerald-billiard',
      name: 'Emerald Billiard',
      isPro: true,
      woodDark: Color(0xFF1E2E1A),
      woodMid: Color(0xFF3A5230),
      woodLight: Color(0xFF6E8A5A),
      felt: Color(0xFF0F5E3A),
      rail: Color(0xFF4A6E3A),
      bumperA: Color(0xFFE8D44C),
      bumperB: Color(0xFFC42E1E),
      sling: Color(0xFFD9C46A),
      laneLit: Color(0xFFFFFF6A),
      laneUnlit: Color(0xFF2E4A30),
      flipper: Color(0xFFE8D44C),
      ivory: Color(0xFFF5F2E4),
      muted: Color(0xFFB4C2A4),
      accent: Color(0xFFE8D44C),
    ),
    PinballThemeDef(
      id: 'crimson-velvet',
      name: 'Crimson Velvet',
      isPro: true,
      woodDark: Color(0xFF2E0E0A),
      woodMid: Color(0xFF5E1E14),
      woodLight: Color(0xFF8A3A24),
      felt: Color(0xFF6E1420),
      rail: Color(0xFF8A4A2E),
      bumperA: Color(0xFFE8B64C),
      bumperB: Color(0xFFF2EAD8),
      sling: Color(0xFFD99A5A),
      laneLit: Color(0xFFFFE08A),
      laneUnlit: Color(0xFF5E2E24),
      flipper: Color(0xFFE8B64C),
      ivory: Color(0xFFF8EDDC),
      muted: Color(0xFFC2A48E),
      accent: Color(0xFFE8B64C),
    ),
    PinballThemeDef(
      id: 'navy-leather',
      name: 'Navy Leather',
      isPro: true,
      woodDark: Color(0xFF1A140E),
      woodMid: Color(0xFF3A2E1E),
      woodLight: Color(0xFF6E5A3A),
      felt: Color(0xFF14243E),
      rail: Color(0xFF5A4A30),
      bumperA: Color(0xFFC9A227),
      bumperB: Color(0xFF8A1E1E),
      sling: Color(0xFFB99B5A),
      laneLit: Color(0xFFFFD76A),
      laneUnlit: Color(0xFF2E3A4E),
      flipper: Color(0xFFC9A227),
      ivory: Color(0xFFF0EAD8),
      muted: Color(0xFF9AA4B4),
      accent: Color(0xFFC9A227),
    ),
    PinballThemeDef(
      id: 'ivory-gold',
      name: 'Ivory & Gold',
      isPro: true,
      woodDark: Color(0xFF4A3A20),
      woodMid: Color(0xFF7A6238),
      woodLight: Color(0xFFB99B5A),
      felt: Color(0xFFF2EAD8),
      rail: Color(0xFF8A744A),
      bumperA: Color(0xFFB03A2E),
      bumperB: Color(0xFF1E4D3B),
      sling: Color(0xFFC9A227),
      laneLit: Color(0xFFFF6B4A),
      laneUnlit: Color(0xFFB4A888),
      flipper: Color(0xFFB03A2E),
      ivory: Color(0xFF2E2410),
      muted: Color(0xFF7A6E52),
      accent: Color(0xFF9C7A1E),
    ),
    PinballThemeDef(
      id: 'copper-hearth',
      name: 'Copper Hearth',
      isPro: true,
      woodDark: Color(0xFF2E1A10),
      woodMid: Color(0xFF5E3A20),
      woodLight: Color(0xFF8A5E3A),
      felt: Color(0xFF3E2A1A),
      rail: Color(0xFF8A5E3A),
      bumperA: Color(0xFFE08A4C),
      bumperB: Color(0xFFB9B9B9),
      sling: Color(0xFFD99A5A),
      laneLit: Color(0xFFFFB46A),
      laneUnlit: Color(0xFF5E4A30),
      flipper: Color(0xFFE08A4C),
      ivory: Color(0xFFF5EEDC),
      muted: Color(0xFFB4A088),
      accent: Color(0xFFE08A4C),
    ),
    PinballThemeDef(
      id: 'vintage-carnival',
      name: 'Vintage Carnival',
      isPro: true,
      woodDark: Color(0xFF3E2410),
      woodMid: Color(0xFF6E4A20),
      woodLight: Color(0xFF9C7440),
      felt: Color(0xFF8A1E24),
      rail: Color(0xFF9C7440),
      bumperA: Color(0xFFFFD76A),
      bumperB: Color(0xFF2E5E8A),
      sling: Color(0xFFE8B64C),
      laneLit: Color(0xFFFFFF8A),
      laneUnlit: Color(0xFF6E3A30),
      flipper: Color(0xFFFFD76A),
      ivory: Color(0xFFF8F0DC),
      muted: Color(0xFFD4B48A),
      accent: Color(0xFFFFD76A),
    ),
    PinballThemeDef(
      id: 'honey-amber',
      name: 'Honey Amber',
      isPro: true,
      woodDark: Color(0xFF3A240E),
      woodMid: Color(0xFF6E4A1E),
      woodLight: Color(0xFFA8783A),
      felt: Color(0xFF8A5E1E),
      rail: Color(0xFF9C7440),
      bumperA: Color(0xFFFFE08A),
      bumperB: Color(0xFF7A3A1E),
      sling: Color(0xFFD9A441),
      laneLit: Color(0xFFFFFF6A),
      laneUnlit: Color(0xFF7A5E30),
      flipper: Color(0xFFFFE08A),
      ivory: Color(0xFF2E2008),
      muted: Color(0xFF6E5A34),
      accent: Color(0xFFD9A441),
    ),
    PinballThemeDef(
      id: 'espresso-noir',
      name: 'Espresso Noir',
      isPro: true,
      woodDark: Color(0xFF0E0906),
      woodMid: Color(0xFF241610),
      woodLight: Color(0xFF4A3220),
      felt: Color(0xFF1A1210),
      rail: Color(0xFF4A3A28),
      bumperA: Color(0xFFD9B36A),
      bumperB: Color(0xFF8A8A8A),
      sling: Color(0xFF9C7A4A),
      laneLit: Color(0xFFFFD76A),
      laneUnlit: Color(0xFF3A2E22),
      flipper: Color(0xFFC99B5F),
      ivory: Color(0xFFF0E8D8),
      muted: Color(0xFF9A8874),
      accent: Color(0xFFD9B36A),
    ),
  ];

  static PinballThemeDef byId(String id, {PinballThemeDef? custom}) {
    if (id == 'custom' && custom != null) return custom;
    for (final t in all) {
      if (t.id == id) return t;
    }
    return all.first;
  }

  static bool isProTheme(String id) =>
      all.any((t) => t.id == id && t.isPro);
}
